# Generated by Django 6.0.2 on 2026-02-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pub_time', 'name']},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book_table',
        ),
    ]
